### PR TITLE
About page UI updated

### PR DESCRIPTION
**Pull request by Hemant-Lohar**
Updated About page UI with Skills. added icons about skills.

### CODE REVIEW

**Review by prasad-chavan1 — CHANGES_REQUESTED** [review]
Responsiveness that icons should be wrapped i mean flex-direction: wrap; then ill merge

**Comment by prasad-chavan1** [comment]
@Hemant-Lohar why that menu bar on about page goes as desktop mode ??checkout that bug and fix

**Review by prasad-chavan1 — CHANGES_REQUESTED** [review]
Still it giving error as responsiveness

**Comment by Hemant-Lohar** [comment]
Fixed issues with icons and responsiveness.

**Comment by prasad-chavan1** [comment]
> Fixed issues with icons and responsiveness.

Good job @Hemant-Lohar 💌

**Pull request merged**
